services:
  db:
    image: postgres:17
    container_name: bank-db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - bank_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./bank-backend
    container_name: bank-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8080
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./bank-frontend
    container_name: bank-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  bank_db_data:
